export default  {
	GET_ALL_CATEGORIES: 'GET_ALL_CATEGORIES',
	GET_ALL_POSTS: 'GET_ALL_POSTS',
	FILTER_POSTS_BY_CATEGORY: 'FILTER_POSTS_BY_CATEGORY',
	GET_COMMENTS_FOR_POST: 'GET_COMMENTS_FOR_POST',
	GET_COMMENT_DETAILS: 'GET_COMMENT_DETAILS',
	EDIT_POST: 'EDIT_POST',
	EDIT_COMMENT_DETAILS: 'EDIT_COMMENT_DETAILS',
	DELETE_COMMENT: 'DELETE_COMMENT',
	DELETE_POST: 'DELETE_POST',
	VOTE_FOR_POST: 'VOTE_FOR_POST',
	VOTE_FOR_COMMENT: 'VOTE_FOR_COMMENT',
	ADD_POST: 'ADD_POST',
	ADD_COMMENT: 'ADD_COMMENT',
	SORT_POSTS:'SORT_POSTS',
	OPEN_DIALOG:'OPEN_DIALOG',
	CLOSE_DIALOG:'CLOSE_DIALOG',
	OPEN_COMMENTS_DIALOG:'OPEN_COMMENTS_DIALOG',
	CLOSE_COMMENTS_DIALOG:'CLOSE_COMMENTS_DIALOG'

};
